name: virtual_dom
description: The Virtual DOM is a small, lightweight, low-level implementation of the Virtual DOM.
repository:  https://github.com/mezoni/virtual_dom
version: 0.1.11
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  test: ^1.21.5
